#! /bin/bash

FILE_NAME=$1
INTERFACE_NAME=$2

clang++ \
 -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS \
 -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D_GNU_SOURCE \
 -fsyntax-only \
 -Xclang -load -Xclang /usr/lib/libclang_active_object_generator.so \
 -Xclang -plugin -Xclang clang_active_object \
 -Xclang -plugin-arg-clang_active_object -Xclang ${INTERFACE_NAME} \
 -Xclang -plugin-arg-clang_active_object -Xclang /usr/share/clang-active-object-generator/ActiveObject.mustache \
 ${FILE_NAME}